FIG_SAVE_PATH: /Users/joshuamiller/Documents/Lancaster/Figs
HISTORY_DATA:
- ozone
- temp
- u-wind
- v-wind
- lon
- lat
- time
HIST_TARG:
  history_len: 5
  target_len: 1
HYPERPARAMETERS:
  conv_hyperparams_dict:
    batch_size: 32
    epochs: 10000
    num_filters: 64
    num_trans: 1
  convlstm_hyperparams_dict:
    batch_size: 32
    epochs: 10000
    num_filters: 64
    num_trans: 1
  denoise_hyperparams_dict:
    batch_size: 32
    epochs: 10000
    inner_filters: 128
    latent_size: 256
    middle_filters: 64
    num_latent_layers: 0
    num_trans: 0
    outer_filters: 64
  dense_hyperparams_dict:
    batch_size: 32
    epochs: 10000
    num_neurons: 100
    num_trans: 0
  gb_hyperparams_dict:
    early_stopping_rounds: 100
    max_depth: 24
    num_boost_round: 10000
    subsample: 0.5
  lstm_hyperparams_dict:
    batch_size: 32
    epochs: 10000
    lstm_units: 512
    num_trans: 0
  rbdn_hyperparams_dict:
    batch_size: 32
    epochs: 200
    num_inner_filters: 128
    num_outer_filters: 64
  rf_hyperparams_dict:
    device: cpu
    max_depth: 24
    num_trees: 200
    subsample: 0.5
    use_xgboost: True
  split_hyperparams_dict:
    batch_size: 32
    epochs: 200
    hidden_size: 128
    num_outer_filters: 64
    presplit_filters: 256
  trans_hyperparams_dict:
    batch_size: 32
    epochs: 100
    num_heads: 4
    num_neurons: 100
MODEL_FIG_SAVE_PATH: /Users/joshuamiller/Documents/Python Files/Wildfire_Ozone/SavedModels/Figs
MODEL_PRED_PATH: /Users/joshuamiller/Documents/Lancaster/SimulationResults
MODEL_SAVE_PATH: /Users/joshuamiller/Documents/Lancaster/SavedModels
MODEL_TYPE: Conv
PATIENCE: 100
REGION: Whole_Area
RF_OFFSET: 1
TARGET_DATA:
- ozone
TIME_WINDOW:
  end_date: '2022-07-31'
  start_date: '2018-04-30'
TRAIN_TEST: 0.75